server:
  port: 8000
 
logging:
  level:
    root: info

spring:
  application:
    name: TestService
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/