server:
  port: 80
 
logging:
  level:
    root: info
    
spring:
  datasource:
    url:  jdbc:mysql://localhost/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root 
    password: ossera 
    
